### ISSUE TITLE
Unrecognized manifest key

### ISSUE THREAD

**Issue by pwnyprod** [ben0bi/unl0gin#2]
Hey,

is this Notice normal for unsigned Extensions?
Got this Notice on the [chrome://extensions/](chrome://extensions/) Page after installing the Extension. The Extension works but i just want to let you know this.

```
There were warnings when trying to install this extension:
Unrecognized manifest key 'applications'.
```

**Comment by ben0bi** [comment]
Look, I am to lazy and I hate the policies today that everything has to be signed and backsigned and double encrypted and reviewed by exactly eleven coders and whatsoever. Short: I did NOT compile it. There is NO manifest. As long as it works, I do not bother about such stuff. Please enable "Debug" in the Chrome Settings-->Plugins and then it should work. It throws an alarmbox on each start of the browser: "Cancel debug mode?"...click "No" or compile it yourself. I am a coder, not an admin, though every-"one" (companys, mostly) thinks, we love to fiddle out such nonsense crap like signing an app. If there is an app, it has to run or not, no matter if it is...ahrgl, just think yourself the end of this mockery. Think of me like of  a coder from the DOS days (about 1990), where there was not even a login for your desktop machine....*ben0bi out*
